"""
PR 7 — XGBoost quantile training script.

Loads the parquet generated by generate_training_data.py, trains three
XGBoost quantile models (P10 / P50 / P90), and saves them as .joblib files.

Usage:
    python scripts/train_solar.py                  # train and save models
    python scripts/train_solar.py --check-only     # load existing models, validate with 5-row predict

Logs go to stdout and to logs/train_solar.log (created automatically).
If something fails, share the full log file with Claude for diagnosis.
"""

from __future__ import annotations

import argparse
import logging
import sys
import traceback
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

# ── Logging setup ──────────────────────────────────────────────────────────────

LOG_DIR = Path(__file__).parent.parent / "logs"
LOG_DIR.mkdir(exist_ok=True)
LOG_FILE = LOG_DIR / "train_solar.log"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_FILE, mode="w", encoding="utf-8"),
    ],
)
log = logging.getLogger(__name__)

# ── Paths ──────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent.parent
DATA_PATH = ROOT / "data" / "solar_training.parquet"
MODEL_DIR = ROOT / "models" / "solar"

MODEL_FILES = {
    0.1: MODEL_DIR / "generic_v1_p10.joblib",
    0.5: MODEL_DIR / "generic_v1_p50.joblib",
    0.9: MODEL_DIR / "generic_v1_p90.joblib",
}

# ── Import FEATURE_COLUMNS from app (single source of truth) ──────────────────

sys.path.insert(0, str(ROOT))
try:
    from app.features import FEATURE_COLUMNS
    log.info("Imported FEATURE_COLUMNS from app.features: %s", FEATURE_COLUMNS)
except ImportError as e:
    log.critical("Cannot import app.features — is your working directory reip-ml/? Error: %s", e)
    sys.exit(1)

LABEL_COLUMN = "generation_kwh"

# ── XGBoost hyperparameters ────────────────────────────────────────────────────

XGBOOST_PARAMS = {
    "n_estimators": 200,
    "max_depth": 5,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "tree_method": "hist",   # fast, CPU-friendly
    "random_state": 42,
}


# ── Data loading ───────────────────────────────────────────────────────────────

def load_data() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load parquet, apply chronological 80/20 split, return (X_train, X_val, y_train, y_val)."""
    log.info("Loading data from: %s", DATA_PATH)
    if not DATA_PATH.exists():
        raise FileNotFoundError(
            f"Training data not found at {DATA_PATH}. "
            "Run: python scripts/generate_training_data.py"
        )

    df = pd.read_parquet(DATA_PATH)
    log.info("Loaded %d rows × %d columns", *df.shape)
    log.info("Cities (by latitude count): %s",
             df.groupby("latitude")["latitude"].count().to_dict())
    log.info("Date range: %s → %s", df["timestamp"].min(), df["timestamp"].max())
    log.info(
        "Label stats: min=%.2f  mean=%.2f  median=%.2f  max=%.2f  zeros=%d (%.1f%%)",
        df[LABEL_COLUMN].min(),
        df[LABEL_COLUMN].mean(),
        df[LABEL_COLUMN].median(),
        df[LABEL_COLUMN].max(),
        (df[LABEL_COLUMN] == 0).sum(),
        100 * (df[LABEL_COLUMN] == 0).mean(),
    )

    # Validate all FEATURE_COLUMNS are present
    missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(
            f"Parquet is missing columns: {missing}. "
            "Re-run generate_training_data.py to rebuild."
        )
    log.info("All %d FEATURE_COLUMNS present in parquet.", len(FEATURE_COLUMNS))

    # Sort by timestamp for chronological split (critical — no random shuffle)
    df = df.sort_values("timestamp").reset_index(drop=True)

    split_idx = int(len(df) * 0.8)
    train_df = df.iloc[:split_idx]
    val_df   = df.iloc[split_idx:]

    log.info(
        "Chronological split: train=%d rows (%.0f%%), val=%d rows (%.0f%%)",
        len(train_df), 100 * len(train_df) / len(df),
        len(val_df),   100 * len(val_df)   / len(df),
    )
    log.info("Train period: %s → %s", train_df["timestamp"].min(), train_df["timestamp"].max())
    log.info("Val   period: %s → %s", val_df["timestamp"].min(),   val_df["timestamp"].max())

    X_train = train_df[FEATURE_COLUMNS].to_numpy(dtype=np.float64)
    X_val   = val_df[FEATURE_COLUMNS].to_numpy(dtype=np.float64)
    y_train = train_df[LABEL_COLUMN].to_numpy(dtype=np.float64)
    y_val   = val_df[LABEL_COLUMN].to_numpy(dtype=np.float64)

    log.info("X_train shape: %s  X_val shape: %s", X_train.shape, X_val.shape)
    return X_train, X_val, y_train, y_val


# ── Training ───────────────────────────────────────────────────────────────────

def train_quantile(
    alpha: float, X_train: np.ndarray, y_train: np.ndarray,
    X_val: np.ndarray, y_val: np.ndarray,
) -> object:
    """Train one XGBoost quantile model and log validation metrics."""
    try:
        from xgboost import XGBRegressor
    except ImportError:
        log.critical("xgboost not installed. Run: pip install xgboost")
        sys.exit(1)

    label = f"P{int(alpha * 100):02d}"
    log.info("── Training %s (alpha=%.1f) ───────────────────────────────────", label, alpha)

    model = XGBRegressor(
        objective="reg:quantileerror",
        quantile_alpha=alpha,
        **XGBOOST_PARAMS,
    )

    log.info("[%s] Fitting on %d training rows ...", label, len(X_train))
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )

    # Validation metrics
    preds = model.predict(X_val)
    residuals = y_val - preds
    mae = float(np.mean(np.abs(residuals)))
    rmse = float(np.sqrt(np.mean(residuals ** 2)))

    # Quantile coverage: fraction of actuals below predicted quantile
    coverage = float(np.mean(y_val <= preds))
    log.info(
        "[%s] Val MAE=%.2f kWh  RMSE=%.2f kWh  Coverage=%.3f (target=%.1f)",
        label, mae, rmse, coverage, alpha,
    )
    if abs(coverage - alpha) > 0.1:
        log.warning(
            "[%s] Coverage %.3f is more than 10pp away from target %.1f — "
            "model may be miscalibrated. Consider tuning n_estimators or learning_rate.",
            label, coverage, alpha,
        )
    else:
        log.info("[%s] Coverage within acceptable range. ✓", label)

    return model


# ── Smart persistence baseline ─────────────────────────────────────────────────

def compute_smart_persistence_rmse(X_val: np.ndarray, y_val: np.ndarray) -> float:
    """Compute RMSE of smart persistence baseline on validation set.

    Smart persistence: predict generation as clear_sky_index_today × clearsky_tomorrow.
    Since we don't have tomorrow's clearsky at this point, we approximate by using
    the current clearsky_index × current clearsky GHI as the baseline prediction.
    This is a lower bound on what smart persistence would achieve with proper lookahead.
    """
    csi_idx = FEATURE_COLUMNS.index("clear_sky_index")
    csi = X_val[:, csi_idx]
    # Proxy: scale label mean by CSI ratio (simple but informative)
    label_mean = np.mean(y_val[y_val > 0]) if np.any(y_val > 0) else 1.0
    baseline_preds = csi * label_mean
    rmse = float(np.sqrt(np.mean((y_val - baseline_preds) ** 2)))
    log.info("Smart persistence proxy RMSE: %.2f kWh (lower RMSE = better than baseline)", rmse)
    return rmse


# ── Save models ────────────────────────────────────────────────────────────────

def save_model(model: object, path: Path, label: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, path)
    size_kb = path.stat().st_size / 1024
    log.info("[%s] Saved → %s (%.1f KB)", label, path, size_kb)


# ── Check-only mode ────────────────────────────────────────────────────────────

def check_only() -> None:
    """Load existing models and run a 5-row smoke test."""
    log.info("CHECK-ONLY mode: loading existing models and running smoke test.")

    for alpha, path in MODEL_FILES.items():
        label = f"P{int(alpha * 100):02d}"
        if not path.exists():
            log.error("[%s] Model file not found: %s", label, path)
            sys.exit(1)
        log.info("[%s] Found: %s", label, path)

    models = {alpha: joblib.load(path) for alpha, path in MODEL_FILES.items()}
    log.info("All 3 models loaded successfully.")

    # Run a 5-row synthetic predict
    n = 5
    rng = np.random.default_rng(0)
    X_smoke = rng.uniform(0, 1, size=(n, len(FEATURE_COLUMNS))).astype(np.float64)
    log.info("Running predict on %d synthetic rows (shape=%s) ...", n, X_smoke.shape)

    for alpha, model in models.items():
        label = f"P{int(alpha * 100):02d}"
        preds = model.predict(X_smoke)
        assert preds.shape == (n,), f"[{label}] Expected shape ({n},) but got {preds.shape}"
        log.info("[%s] Output shape: %s  values: %s", label, preds.shape,
                 [f"{v:.2f}" for v in preds])

    # Check ordering: p10 <= p50 <= p90 on smoke data
    p10 = models[0.1].predict(X_smoke)
    p50 = models[0.5].predict(X_smoke)
    p90 = models[0.9].predict(X_smoke)
    ordering_ok = np.all(p10 <= p50 + 1e-3) and np.all(p50 <= p90 + 1e-3)
    if ordering_ok:
        log.info("Quantile ordering P10 ≤ P50 ≤ P90 holds on smoke data. ✓")
    else:
        log.warning(
            "Quantile ordering violated on some rows (quantile crossing). "
            "This is normal for XGBoost quantile regression — clip at inference if needed."
        )

    log.info("CHECK-ONLY passed. ✓")


# ── Main ───────────────────────────────────────────────────────────────────────

def main(check: bool) -> None:
    log.info("=" * 70)
    log.info("train_solar.py  |  check_only=%s", check)
    log.info("FEATURE_COLUMNS (%d): %s", len(FEATURE_COLUMNS), FEATURE_COLUMNS)
    log.info("=" * 70)

    if check:
        check_only()
        return

    X_train, X_val, y_train, y_val = load_data()

    baseline_rmse = compute_smart_persistence_rmse(X_val, y_val)

    trained_models = {}
    for alpha in [0.1, 0.5, 0.9]:
        model = train_quantile(alpha, X_train, y_train, X_val, y_val)
        trained_models[alpha] = model

    # Compare P50 RMSE against baseline
    p50_preds = trained_models[0.5].predict(X_val)
    p50_rmse = float(np.sqrt(np.mean((y_val - p50_preds) ** 2)))
    skill_score = 1.0 - (p50_rmse / baseline_rmse) if baseline_rmse > 0 else 0.0
    log.info("─" * 50)
    log.info("P50 RMSE:            %.2f kWh", p50_rmse)
    log.info("Baseline RMSE:       %.2f kWh", baseline_rmse)
    log.info("Skill score (P50):   %.3f  (target ≥ 0.20 over baseline)", skill_score)
    if skill_score >= 0.20:
        log.info("Skill score target MET. ✓")
    else:
        log.warning(
            "Skill score %.3f is below the 0.20 target. "
            "Consider: more cities in training data, tuning hyperparameters, "
            "or checking for data quality issues in the parquet.",
            skill_score,
        )
    log.info("─" * 50)

    log.info("Saving models ...")
    for alpha, model in trained_models.items():
        label = f"P{int(alpha * 100):02d}"
        save_model(model, MODEL_FILES[alpha], label)

    log.info("All 3 models saved. Running check-only smoke test ...")
    check_only()

    log.info("=" * 70)
    log.info("TRAINING COMPLETE ✓")
    log.info("Log saved to: %s", LOG_FILE)
    log.info("=" * 70)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train REIP XGBoost solar quantile models")
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Load existing models and run a 5-row smoke test only (no training).",
    )
    args = parser.parse_args()

    try:
        main(check=args.check_only)
    except KeyboardInterrupt:
        log.warning("Interrupted by user.")
        sys.exit(130)
    except Exception:
        log.critical("Unhandled exception — traceback:")
        log.critical(traceback.format_exc())
        log.critical("Check the log at: %s", LOG_FILE)
        sys.exit(1)
